### ISSUE TITLE
Not transforming color function "hwb()" with stage-0

### ISSUE THREAD

**Issue by shallinta** [csstools/postcss-preset-env#108]
I still got "color: hwb(...)" in my chrome which is not able to recognize it. 

My chrome browser version is above 71 beta.

I'm using webpack and postcss-loader@3.0.0, and postcss@7.0.6, postcss-preset-env@6.4.0.

I config postcss with a config file `.postcssrc.js`, content as following:

```javascript
module.exports = {
  parser: false,
  plugins: {
    'postcss-preset-env': {
      stage: 0,
      browsers: [
        '> 1%',
        'Android >= 4.4',
        'IOS >= 7',
        'ie >= 9'
      ]
    }
  }
};
```

In addition, color function "gray()" works well. And there is no package "postcss-color-hwb" found in node_modules directory while "postcss-color-gray" is found.

**Comment by marcofugaro** [comment]
The `color-mod-function` plugin is not working for me either, it works only if I explicitly specify `colorModFunction` in the plugin list after `postcssPresetEnv`,

**Comment by pascalduez** [comment]
> The color-mod-function plugin is not working for me either, it works only if I explicitly specify colorModFunction in the plugin list after postcssPresetEnv,

See https://github.com/csstools/cssdb/commit/96bb8e8547a946dcbc29b866ac13330fed6ca04b

**Comment by romainmenke** [comment]
Hi @shallinta,

A lot has changed since this issue was opened.
This repo has been moved to https://github.com/csstools/postcss-plugins

There is an ongoing effort for `hwb` support here : https://github.com/csstools/postcss-plugins/pull/70

Going to close this issue as we will archive this repo which prevents further discussion.
Feel free to open a new issue with concrete examples in the new repo.
