### ISSUE TITLE
preset-env much slower than cssnext because of browserslist

### ISSUE THREAD

**Issue by AndreKR** [csstools/postcss-preset-env#117]
I am comparing a build of a small Vue.js application with _postcss-cssnext_ vs. _postcss-preset-env_. On my machine the build takes about 20 s with _cssnext_ and 34 s with _preset-env_.

Here's a direct comparison (same zoom factor):

![cssnext](https://user-images.githubusercontent.com/1188538/53511274-5a9ed000-3ac0-11e9-935e-659c5e0286c6.png)

![preset-env-zoom](https://user-images.githubusercontent.com/1188538/53511288-612d4780-3ac0-11e9-99c3-0dbdc5280a87.png)

The difference in time required :yum: for the `require()` is probably because _preset-env_ has many many more recursive requirements, I'm going to ignore that for now and concentrate on the difference in build time. So, where is it spending all of its time...

Here's a zoomed in view of the area marked in black in the image above:

![2019-02-27-18-45-36-chrome](https://user-images.githubusercontent.com/1188538/53511614-19f38680-3ac1-11e9-977a-3f67ef53b8da.png)

It seems to spend a lot of time in a function called `browserslist`. I'm wondering if maybe it's possible to cache the results of that somehow?

Here's the relevant part of my webpack config:

```javascript
{
	test: /\.css$/,
	use: [
		'vue-style-loader',
		{ loader: 'css-loader', options: { importLoaders: 2 } },
		{
			loader: 'postcss-loader',
			options: {
				ident: 'postcss',
				plugins: () => [
					require('postcss-preset-env')({ stage: 0 })
				]
			}
		}
	]
}
```

**Comment by jonathantneal** [comment]
I see 2 spots we could optimize the results.

1. `supportedBrowsers`, where browsers supported by the configuration could be cached by the `result.root.source.input.file` string @ https://github.com/csstools/postcss-preset-env/blob/master/src/postcss.js#L88-L91
2. `supportedFeatures`, where features supported by the stage and browsers could be cached by the `feature.browsers` object @ https://github.com/csstools/postcss-preset-env/blob/master/src/postcss.js#L96-L98

And since `supportedBrowsers` is only in the service of `supportedFeatures`, we could encapsulate these into a single function with caching.

What do you think? Could this be a job for WeakMap?

**Comment by AndreKR** [comment]
I'm not sufficiently familiar with how postcss and postcss-preset-env work to have an opinion about that. But if you have a patch I would be happy to test it and create a new CPU profile.

**Comment by kblomster** [comment]
Dang, I wish I had looked at the issue list this morning because I just spent some time creating [a small demonstration repo](https://github.com/kblomster/preset-env-expensive-browserinit-demo) in preparation to create an issue for exactly the same problem. I'm in exactly the same boat as you @AndreKR - Vue application, lots of small components with scoped CSS, which means a lot of small CSS files. Webpack was getting annoyingly slow so I sat down and profiled it and came to the exact same conclusion - most of the build time is spent instantiating browserslist over and over again.

It gets really expensive if you have a lot of CSS (pseudo-)files, because as @jonathantneal says, `browserslist()` gets called at least `number_of_processed_files * number_of_staged_features` times, plus potentially a number of additional times per staged feature (depending on if `supportedBrowsers.some()` terminates on the first iteration or not).

In the demo repo I made 100 small CSS files (total around 2500 lines) which get compiled with webpack, and the whole thing takes over 35 seconds on my machine. When I tried moving the two operations mentioned by @jonathantneal to the outer scope and removing the `path` argument (see [this commit in my forked repo](https://github.com/kblomster/postcss-preset-env/commit/2578b1d13b663631f699127b5678f5bcf9cdc2f8)), build time was reduced to 1.5 seconds while the output remains identical.

Now, I realize why `supportedBrowsers` is checked on a per-file basis, and the commit above is only an experimental proof-of-concept, but I think it would be nice to at least have an option to make `postcss-preset-env` assume that the list of supported browsers will be constant for the lifetime of the plugin (in my case, the list of supported browsers is the same for all applications in the entire company, even). For my use case I don't think using the input file as a cache key would help at all, because we really do have a lot of small input files.

What do you think? Would it be acceptable to introduce an option flag for this? In fact, maybe passing the `browsers` option explicitly instead of relying on detection of a browserslist config should automatically enable an optimization like that?

**Comment by jonathantneal** [comment]
@kblomster, wow, I absolutely love the research you’ve both done, and I can absolutely understand adding this option, @kblomster.

**Comment by kblomster** [comment]
Great to hear! I'll see about making a pull request for something like that, then. :)

**Comment by jonathantneal** [comment]
Upon further inspection, it doesn’t look like it is necessarily documented or expected behavior to reference each input file rather than the current working directory. I think we can just move it.

Would you mind reviewing https://github.com/csstools/postcss-preset-env/pull/118 ?

**Comment by kblomster** [comment]
Wow, what a response time! ⚡️ Thanks a ton! I'll take a look immediately.

**Comment by jonathantneal** [comment]
This has been fixed and published in v6.6.0. @AndreKR, @kblomster, could you provide some stats on whether or how much things have improved?

**Comment by kblomster** [comment]
With a rather minimal set of features enabled (stage 3 plus the color-mod function), and something like 500 CSS (pseudo-)files, a full production build with cold caches has gone from around 120 seconds to around 80 seconds (most of the time is now spent on Babel and minification, which is expected). A full production build with Babel and Terser cached used to take over a minute, but is now under 30 seconds. 🎉

**Comment by AndreKR** [comment]
For me it didn't change anything. This is because for some reason the plugin gets instantiated (if that is the right term) many times, so each time the browserslist is still executed. I don't (yet) know enough about postcss-loader to say why this happens.

This is the full time _postcss-preset-env_ runs:

![image](https://user-images.githubusercontent.com/1188538/53585769-fbf05980-3b86-11e9-8743-9b3351c4ebd4.png)

And here is a zoomed in view of the period marked in black above:

![image](https://user-images.githubusercontent.com/1188538/53585863-36f28d00-3b87-11e9-9197-1d4a66ddbc6b.png)

As you can see, `postcss$1.plugin.opts` is called many many times. It is called once per _<I haven't figured this out>_.

**Comment by kblomster** [comment]
@AndreKR Does it improve if you change your webpack config to something like this?

```javascript
const postcssPresetEnv = require('postcss-preset-env');

module.exports = {
  // lots of stuff omitted...
  use: [
    // vue-style-loader, css-loader...
    {
      loader: 'postcss-loader',
      options: {
        plugins: [
          postcssPresetEnv({ stage: 0 })
        ]
      }
    }
  ],  
```

Passing the plugins as a function is useful if you want to use different options depending on which loader is used, but you're not using that functionality in your example.

**Comment by AndreKR** [comment]
Yes, it does! Down to 22s (2 more than cssnext, but still > 15s less than the old version).

I don't even need to extract the `require()` changing the function to an array does the trick.

I copied that code from [here](https://github.com/postcss/postcss-loader#plugins). When would I use a function/what is in that `loader` variable?

**Comment by kblomster** [comment]
@AndreKR I have never used it myself, but as far as I understand it, in the context of webpack the argument to that function is a [webpack loader context](https://webpack.js.org/api/loaders/#the-loader-context), or more specifically the loader context for the postcss instance processing a given file. As far as I can tell from the postcss-loader documentation, the idea seems to be that it can be useful if you need your plugins to have configuration options that depend on something that varies between different files processed with the same webpack rule (such as for example the path of the file being processed).

In my case though (and also in yours, as far as I can tell), that creates exactly the effect I don't want - postcss-preset-env is re-created for each file processed.
