### ISSUE TITLE
Nesting rules not being polyfilled at stage 2

### ISSUE THREAD

**Issue by typhoon2099** [csstools/postcss-preset-env#169]
Using postcss-preset-env with no options should default to stage 2, but the nesting ruhles are not being polyfilled, which is currently at stage 1. Using the [playground](https://preset-env.cssdb.org/playground) it is only polyfilled at stage 0. I would expect this to be polyfilled at stages 2, 3, and 4, but not at 0, and 1.

**Comment by lostfictions** [comment]
Stages go up in stability, not down, same as Babel and TC39 proposals. So "polyfilling stage 2" means polyfilling proposals which are _at least_ stage 2 -- that is, nesting would not be included.

Agreed that this is very poorly explained, and I think it's exacerbated by the fact that, unlike Babel and JS, browsers will just happily ignore valid CSS instead of failing fast on invalid syntax. Generally I've had a lot of frustrations with preset-env's documentation, despite the fact that it's in use by some huge commercial software projects -- I wish some of them could help pay someone to document it a bit better!

**Comment by jonathantneal** [comment]
It’s refreshing to read how well you get it, @lostfictions. I’m very sorry for how the flaws of this project negatively affect folks. This personal project has been adopted quite thoroughly without even being fleshed out like a project I’d expect to be available at this scale.

@typhoon2099, just confirming that the stages go up. The underlying confusion is a fault of the documentation. I intend to improve the documentation when I have time to revisit it. These days I’m mostly just using this tool, tho I’m probably a bit subpar at that.

This project is still powered by a very flawed person. There is no sponsorship, no oversight, nobody wants the pressure, and all the orgs are pretend because nobody would use software written by me. When entertain such a hope I’m told variations of "then stop writing it or stop complaining.” Once I’m done helping work out some underlying issues in PostCSS itself, I intend to push updates more regularly back to this project, which would include significant improvements to documentation based on my experience seeing people use it.

PRs are welcome. Nagging me is also welcome. Again, I don’t want these tools to frustrate anyone, ever, but I’ll admit that it’s also comforting to see people care.
