### ISSUE TITLE
Update `postcss-logical`

### ISSUE THREAD

**Issue by charsboo** [csstools/postcss-preset-env#179]
v.4+ of `postcss-logical` added some useful properties (e.g., `border-*-*-radius`) and fixes (e.g., “…issue w/ `block-size`”). Is it possible to update from the packaged v.3?

**Comment by mherchel** [comment]
👍

**Comment by mherchel** [comment]
+1 on this. We're trying to bring `postcss-preset-env` into Drupal core as part of the new default Olivero theme, and am running into issues with properties like `border-start-start-radius` not being converted.

cross-reference https://www.drupal.org/project/olivero/issues/3172453

**Comment by jonathantneal** [comment]
PostCSS Logical is the plugin I have prioritized, as I am working full time on open source this week (i.e. I’m unemployed!). The issue is “harder” to resolve because there are two contributing factors.

1. This tool requires multiple CSS parsers, and they are not very interoperable. I am trying to solve this problem upstream in PostCSS.
2. This tool is often used alongside browser compatibility data via browserslist, and that information was incorrect. I mostly solved this problem upstream in caniuse.

I am always open to stop-gap fixes.

**Comment by mherchel** [comment]
Thanks for the update (and thanks for all the FOSS contributions ❤️ )  😀

**Comment by bakura10** [comment]
Any news regarding this issue? We also need the dependency to be upgraded to have the border-radius properly ouputed.

Thanks :)
