### ISSUE TITLE
Add `aspect-ratio` support

### ISSUE THREAD

**Issue by brielov** [csstools/postcss-preset-env#187]
There is a work in progress draft to finally bring aspect-ratio boxes to CSS, it would be nice to have it baked into this awesome tool. 

MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio

**Comment by madeleineostoja** [comment]
Now that this is supported in all evergreens I'd say this is an essential. I didn't realise this wasn't polyfilled until I tested on an older version of iOS where aspect-ratio wasn't supported.

**Comment by romainmenke** [comment]
This can't be polyfill in `postcss-preset-env` as we would have to make too many assumptions about how the HTML is structured.

I wrote a polyfill for `aspect-ratio` that is used internally at work and most frontend devs have trouble using it because the html (and other CSS) has be just right.

I will consider open sourcing that plugin separate from `postcss-preset-env`.
That gives people the option of using it without causing too much support requests for maintainers of `postcss-preset-env`
