### ISSUE TITLE
With react-app-rewired is not working

### ISSUE THREAD

**Issue by huangliop** [csstools/postcss-preset-env#36]
I use create-app-react create my project.
and use [react-app-rewired ](https://github.com/timarney/react-app-rewired) modify webpack config.
i add postcss-preset-env like this 
```
  config.module.rules[1].oneOf.unshift(
    {
      test: /\.css$/,
      use: [
        require.resolve('style-loader'),
        {
          loader: require.resolve('css-loader'),
          options: {
            modules: true,
            importLoaders: 1,
            localIdentName: '[local]___[hash:base64:5]'
          },
        },
        {
          loader: require.resolve('postcss-loader'),
          options: {
            ident: 'postcss',
            plugins: () => [
              require('postcss-preset-env')({stage:0,browsers:'> 2%'}),
              require('postcss-flexbugs-fixes'),
              autoprefixer({
                browsers: [
                  '>1%',
                  'last 4 versions',
                  'Firefox ESR',
                  'not ie < 9', // React doesn't support IE8 anyway
                ],
                flexbox: 'no-2009',
              }),
            ],
          },
        }
      ]
    }
  );
```

but this not working.

Help me!

**Comment by jonathantneal** [comment]
I’m sorry you’re having issues. While your request is out of scope for this project, I could see how useful something like this is.

Therefore, I’ve created a package to mange using PostCSS plugins in React App Rewired:

https://github.com/jonathantneal/react-app-rewire-postcss

Unfortunately, an author has already published a package with that name, although it doesn’t immediately appear to be that the author published it on purpose. I’ve contacted them to request publishing rights to publish this one.

I’m closing the issue because it is out of scope, but I appreciate you bringing it to my attention, and I hope you’ll find my creating an entire separate project to help you to be a sufficient response. 😄
