### ISSUE TITLE
Stability option

### ISSUE THREAD

**Issue by mrmckeb** [csstools/postcss-preset-env#61]
I have to say that I'm in love with the idea of `postcss-preset-env`, and have used `css-next` in previous projects.

Some parts have been a little frustrating though. As an example, [`color-mod-function`](https://github.com/jonathantneal/postcss-color-mod-function) is brilliant - but has bugs when using with vars, especially those not defined in the same file, which cost me many hours in trying to find a good solution to this. That's not a complain, debugging is part of the job.

I'd propose that in addition to the `stage` option, it could be good to add a `stability` option or index so that developers could chose to use the "trouble-free" parts of postcss-preset-env`, and not use any features that may not be stable*.

* When I say stable, I'm fully aware that some things are completely impossible to do in CSS without official browser support for features, like `color-mod` with variables.

**Comment by jonathantneal** [comment]
I hear ya. I think “stability” is pretty complex to reliably determine.

Stability can be determined by the capability of the plugin, and/or the number of unresolved issues, and/or the time committed to the particular feature, and/or the stability of the specification.

1. Capability of the plugin. Variables are hardly a reliable feature, as we can only polyfill custom properties at the `:root` level, and there isn’t an option in either the custom-properties or color-mod plugins to reference variables from another file. The chief reason this plugin has issues with variables is because the right solution involves me also re-writing the custom properties plugin, which I didn’t originally write, and which is pretty “frankenstein”. I’m also its maintainer for other issues now, due to a lack of maintainers.

2. The number of unresolved issues, and/or the time committed to the particular feature. One of the great things about giving users the ability to experiment with new css features is that they can battle test them. Sometimes the battle tests reveal issues with the polyfill implementation more than the feature itself. That’s one of the reasons you’ve raised this issue. I’ve been thin on investment, especially after assuming maintenance of a host of other plugins. In fact, you might know this project was originally an open issue with cssnext. The only way I think we can solve this issue is by getting myself paid time to work on the project. Otherwise, my family really needs _more_ of my time than less of it, presently.

3. The stability of the specification. Let’s not forget the involvement of the csswg, which I’ve had a surprisingly hard time staying up to date with as a non-member. For instance, did you know they removed `color-mod()` from the spec entirely? I’m on good terms with many members, but I never got so much as a tweet or an email when they removed this, because they owe me nothing. I could close this whole issue on the idea that I have to deprecate it anyway. Did you know the matches plugin is written totally wrong, too? I have an open issue in that plugin for it, and it will probably be me who has to fix it. And did you know that the nesting spec doesn’t yet include nesting media queries? I’ve been leading an issue with the csswg to see if those can be handled together, lest I deprecate that feature.

So, I’m with you in the spirit of this idea, but its practical implications seem too difficult for me to implement as a team of one, with extremely generous but infrequent code contributions from the community.

**Comment by mrmckeb** [comment]
Wow, I did not know that. It's really very hard to keep up, I understand.

I found that it's still in [CSS Color Module Level 4](https://www.w3.org/TR/css-color-4/#funcdef-color-mod) and then this that says it is dead - [Mozilla Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1352756).

I'll close this issue off as I agree with you, I just thought there may have been some clever idea that I hadn't thought of myself. 

I 100% appreciate the effort that you've put in here and think you're doing a great job. What you're working with is a constant moving target, with features that are hard to polyfill - and polyfills that people expect to work with other polyfills.

Let's hope that the CSS Houdini task force and other upcoming features can make polyfilling easier in future.
