### ISSUE TITLE
Merge results from exportTo

### ISSUE THREAD

**Issue by silvenon** [csstools/postcss-preset-env#93]
I'm using `exportTo: './src/styles/exports.js'`, but each plugin that uses this option overrides the file, so the file ends up containing only `customSelectors` because that's the one that runs last. (Same goes for other methods of exporting.) They should be collected somehow.

I want to help with this, but I could use some advice about the strategy.

**Comment by jonathantneal** [comment]
I just thought about this last night after I had tweeted out `exportTo` advice. You are right, and I need to think about this for a minute.

**Comment by silvenon** [comment]
Man, you're fast.

**Comment by silvenon** [comment]
I figured out how to do it for objects without modifying those three plugins, just collect it into an object, but writing files is trickier, I think we need to expose the logic of those plugins for converting objects to file content strings, then within postcss-preset-env concatenate and write down the result.

One idea is to add a second argument to the `exportTo` function, which is an object of functions for converting to file content string:

```js
exportTo: (customProperties, fileContent) => {
  console.log(fileContent.toCss(customProperties))
  /**
   * :root {
   *   --foo: 5;
   *   --bar: 100%;
   * }
   */
}
```

I'm not crazy about this API because we would be exposing something that's probably only useful to postcss-preset-env.

**Comment by mrksbnch** [comment]
@jonathantneal Sorry for bumping this issue but I think this problem is related to either this issue or this one (https://github.com/postcss/postcss-custom-properties/issues/152). If I need to open a separate issue, please let me know.

I have the following entry in my package.json file:

```
"postcss": {
  "plugins": {
    "postcss-preset-env": {
      "features": {
        "custom-properties": {
          "importFrom": [
            {
              "customProperties": {
                "--property-test": "#3FAEFF"
              }
            }
          ]
        },
        "custom-media-queries": {
          "importFrom": [
            {
              "customMedia": {
                "--media-test": "(min-width: 450px)"
              }
            }
          ]
        },
      }
    }
  }
}
```

and while the custom media queries are working just fine (as far as I can see), the config for custom properties is just not working (variables are not replaced). I'm using the latest version of postcss-preset-env (v6.5.0). Anything that I missed in the configuration?

Thanks!

**Comment by silvenon** [comment]
How about this?

```json
"postcss": {
  "plugins": {
    "postcss-preset-env": {
      "importFrom": [
        {
          "customProperties": {
            "--property-test": "#3FAEFF"
          },
          "customMedia": {
            "--media-test": "(min-width: 450px)"
          }
        }
      ],
      "features": {
        "custom-properties": true,
        "custom-media-queries": true
      }
    }
  }
}
```

**Comment by mrksbnch** [comment]
Thanks, I overlooked that part in the documentation and noticed that I stopped at the "feature" option for some reason. However, I just tried that and that also doesn't seem to work for me. Not sure if it's because I'm using the package.json and not a separate config file. But then again, all other settings seem to work fine in package.json.

I'll try to shuffle that around a bit and move the postcss config into a seperate file.
